id: A1A4AEEAE
title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
type: translation
pechas:
- I331D88AA
- I006F01C6
- ID762EB4A
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:50.069061
  last_modified_at: 2023-01-04 13:11:50.069074
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I331D88AA/A072: 5A43
  I006F01C6/4743: 5A43
  ID762EB4A/25A2: 5A43
